apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-trace
spec:
  mode: deployment

  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector

  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      memory_limiter:
        check_interval: 1s        
        limit_percentage: 75      
        spike_limit_percentage: 15 
      batch:
        send_batch_size: 10000    
        timeout: 10s            

    exporters:
      debug: {}
      otlp/jaeger:
        endpoint: jaeger-inmemory-instance-collector.monitoring.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/jaeger, debug]